version: "3.5"
networks:
  nobc-network:
    driver: bridge
services:
  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: elasticsearch
    restart: on-failure
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms40g -Xmx40g"
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - nobc-network

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /data/mysql/conf:/etc/mysql/conf.d
      - /data/mysql/logs:/var/log/mysql
      - /data/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - nobc-network

  redis:
    image: redis:7.0.0
    container_name: redis
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /data/redis/data:/data
      - /data/redis/conf:/usr/local/etc/redis
      - /data/redis/logs:/logs
    ports:
      - 6379:6379
    privileged: true
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - nobc-network

  rabbitmq:
    restart: on-failure
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - /data/rabbitmq/data:/var/lib/rabbitmq
      - /data/rabbitmq/conf:/etc/rabbitmq
    networks:
      - nobc-network

  uwsgi:
    restart: on-failure
    container_name: uwsgi
    image: nobc:latest
    networks:
      - nobc-network
    command:
      - /code/start_uwsgi.sh
  asgi:
    restart: on-failure
    image: nobc:latest
    container_name: asgi
    networks:
      - nobc-network
    command:
      - /code/start_daphne.sh
  nginx:
    restart: on-failure
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/nginx:/etc/nginx
      - /data/frontend:/usr/share/nginx/html
    networks:
      - nobc-network
    depends_on:
      - uwsgi
      - asgi



